export const IS_AUTH = "IS_AUTH";
export const GET_METHOD = "GET_METHOD";
export const GET_MATERIAL = "GET_MATERIAL";
export const SET_CURRENT_USERDATA = "GET_CURRENT_USERDATA";
export const SET_MFG_PROCCESS = "SET_MFG_USERDATA";
export const GET_MFG_PROCCESS = "GET_MFG_USERDATA";
export const DELETE_MFG_PROCCESS = "DELETE_MFG_USERDATA";
